/**
 * Salesforce Webhook Registrations — Baton
 *
 * Endpoint that the SF managed package v0.3+ Apex calls on its first webhook
 * dispatch to exchange a one-time bootstrap token for a persisted HMAC secret.
 *
 *   POST /api/salesforce/webhook-registrations
 *   Headers:
 *     Idempotency-Key: <opaque string, typically `<sfOrgId>_<webhookKey>_<bootstrapToken>`>
 *   Body:
 *     {
 *       webhookKey: string,        // from URL path: /api/webhooks/rule/<webhookKey>
 *       bootstrapToken: string,    // from URL query: ?bootstrap=<bootstrapToken>
 *       sfOrgId: string,           // Salesforce Org Id (15- or 18-char)
 *       generatedSecret: string,   // base64-encoded 256-bit HMAC secret, generated by Apex
 *       packageVersion?: string    // e.g. "0.3.0-1" — for telemetry/troubleshooting
 *     }
 *
 *   Response 200 (success or idempotent replay):
 *     {
 *       status: "registered",
 *       webhookId: string,
 *       secretVersion: number,
 *       expiresAt: string | null
 *     }
 *
 *   Errors:
 *     400 — payload validation
 *     401 — bootstrap token expired or webhookKey mismatch
 *     404 — bootstrap token / webhookKey not found
 *     409 — token already redeemed by a different request
 *
 * Secret keying:
 *   Secrets are persisted under the composite map key `<sfOrgId>#<webhookKey>`
 *   in OrgApp.sfRegistrations — one independent secret per automation rule per
 *   SF org, matching the Apex package's per-webhookKey secret cache. (The
 *   original bare-`<sfOrgId>` keying shared one secret across ALL rules of an
 *   app, so a second rule's registration silently invalidated the first
 *   rule's HMAC — deterministic 401 "Invalid signature".) Legacy bare entries
 *   remain readable by rule.ts as a fallback.
 *
 * Crash-window self-heal:
 *   Token redemption (which caches the registration response) and the OrgApp
 *   secret write are separate DDB operations. If the process dies in between,
 *   the token is redeemed but no secret is stored — the Apex retry would get
 *   a fake-successful idempotent replay and every webhook would 401 forever.
 *   The token therefore carries a `persisted` flag, set only after the OrgApp
 *   write; a replay that finds `persisted !== true` re-persists the cached
 *   secret before responding.
 */

import { Router, Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';
import { GetCommand, QueryCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';
import { getDocClient, TableNames } from '../db/client';
import { encryptToken } from '../lib/encryption';
import { sfRegKey, SfRegistrationEntry } from '../lib/sf-registration-key';
import { logInfo, logWarn } from '../lib/logger';
import { AutomationRule, OrgApp, BootstrapToken } from '../lib/types';
import {
  redeemBootstrapToken,
  markBootstrapTokenPersisted,
} from '../services/bootstrap-token.service';
import { NotFoundError, ValidationError } from '../middleware/error-handler';

const router = Router();

const registrationSchema = z.object({
  webhookKey: z.string().length(64).regex(/^[a-f0-9]+$/),
  bootstrapToken: z.string().min(20).max(128),
  sfOrgId: z.string().min(15).max(18).regex(/^[0-9A-Za-z]+$/),
  generatedSecret: z.string().min(20).max(256),
  packageVersion: z.string().max(32).optional(),
});

/** Resolve the OrgApp linked to a rule — by appId, falling back to appSlug. */
async function resolveOrgAppForRule(rule: AutomationRule): Promise<OrgApp | undefined> {
  const docClient = getDocClient();
  let app: OrgApp | undefined;

  if (rule.appId) {
    const appResult = await docClient.send(new GetCommand({
      TableName: TableNames.ORG_APPS,
      Key: { id: rule.appId },
    }));
    app = appResult.Item as OrgApp | undefined;
  }

  if (!app && rule.appSlug) {
    const appResult = await docClient.send(new QueryCommand({
      TableName: TableNames.ORG_APPS,
      IndexName: 'orgId-index',
      KeyConditionExpression: 'orgId = :orgId',
      FilterExpression: 'appSlug = :slug AND #st = :active',
      ExpressionAttributeValues: { ':orgId': rule.orgId, ':slug': rule.appSlug, ':active': 'active' },
      ExpressionAttributeNames: { '#st': 'status' },
    }));
    app = (appResult.Items?.[0] as OrgApp) || undefined;
  }

  return app;
}

/**
 * Write one registration entry under the composite key.
 * DynamoDB doesn't allow setting a parent map AND its sub-attribute in a
 * single UpdateExpression. Two-step:
 *   1) Initialize the map if missing (no-op if already exists).
 *   2) Set the per-(sfOrgId, webhookKey) slot under it.
 */
async function persistSfRegistration(
  appId: string,
  regKey: string,
  registration: SfRegistrationEntry,
): Promise<void> {
  const docClient = getDocClient();

  await docClient.send(new UpdateCommand({
    TableName: TableNames.ORG_APPS,
    Key: { id: appId },
    UpdateExpression: 'SET sfRegistrations = if_not_exists(sfRegistrations, :empty)',
    ExpressionAttributeValues: { ':empty': {} },
  }));

  await docClient.send(new UpdateCommand({
    TableName: TableNames.ORG_APPS,
    Key: { id: appId },
    UpdateExpression: 'SET sfRegistrations.#regKey = :reg',
    ExpressionAttributeNames: { '#regKey': regKey },
    ExpressionAttributeValues: { ':reg': registration },
  }));
}

export async function handleSfRegistration(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const idempotencyKey = req.header('Idempotency-Key') || req.header('idempotency-key');
    if (!idempotencyKey || idempotencyKey.length < 8 || idempotencyKey.length > 256) {
      throw new ValidationError('Idempotency-Key header is required (8–256 chars)');
    }

    const payload = registrationSchema.parse(req.body);
    const docClient = getDocClient();
    const regKey = sfRegKey(payload.sfOrgId, payload.webhookKey);

    // ─── 1. Resolve the AutomationRule by webhookKey ─────────
    const ruleResult = await docClient.send(new QueryCommand({
      TableName: TableNames.AUTOMATION_RULES,
      IndexName: 'webhookKey-index',
      KeyConditionExpression: 'webhookKey = :wk',
      ExpressionAttributeValues: { ':wk': payload.webhookKey },
    }));

    if (!ruleResult.Items || ruleResult.Items.length === 0) {
      logWarn('SF registration: unknown webhookKey', { webhookKey: payload.webhookKey.substring(0, 8) + '...' });
      throw new NotFoundError('Webhook endpoint');
    }

    const rule = ruleResult.Items[0] as AutomationRule;

    if (rule.status === 'disabled' || rule.status === 'error') {
      logWarn('SF registration: automation is disabled', { ruleId: rule.id, status: rule.status });
      throw new NotFoundError('Webhook endpoint'); // 404 (not 403) to avoid leaking rule state
    }

    // ─── 2. Atomically redeem the bootstrap token ────────────
    // This locks the token to (sfOrgId, idempotencyKey). On idempotent retry
    // we get the cached response back.
    //
    // The `secret` field echoes back the effective HMAC value stored on the
    // backend. On idempotent replay, Apex's locally-generated secret may
    // differ (e.g. if Apex retried after a local DML failure regenerated it),
    // so Apex must trust THIS value, not its own. Cleartext over HTTPS — same
    // trust boundary as the inbound `generatedSecret`. Bootstrap-token TTL
    // (24h) bounds the storage window; DDB encrypts at rest.
    const webhookId = `wh_${uuidv4()}`;
    const secretVersion = 1; // v0.3 ships with single-version; rotation in v0.4

    const responseBody: NonNullable<BootstrapToken['registrationResponse']> = {
      status: 'registered',
      webhookId,
      secret: payload.generatedSecret,
      secretVersion,
      expiresAt: null,
    };

    const { isIdempotentReplay, token } = await redeemBootstrapToken({
      tokenId: payload.bootstrapToken,
      webhookKey: payload.webhookKey,
      idempotencyKey,
      sfOrgId: payload.sfOrgId,
      registrationResponse: responseBody,
    });

    if (isIdempotentReplay) {
      // Trust the cached response only if the original request actually
      // persisted the secret. `persisted !== true` covers two cases:
      //   a) the original request crashed between redemption and the OrgApp
      //      write (flag is false) — without healing, every webhook from this
      //      SF org would 401 forever while Apex believes it is registered;
      //   b) tokens redeemed before the `persisted` flag existed (undefined) —
      //      re-writing the same secret is a harmless no-op that additionally
      //      migrates the entry from legacy bare-sfOrgId to composite keying.
      const cachedResponse = token.registrationResponse;
      if (token.persisted !== true && cachedResponse) {
        const app = await resolveOrgAppForRule(rule);
        if (!app) {
          logWarn('SF registration: no OrgApp found on replay self-heal', {
            ruleId: rule.id,
            appSlug: rule.appSlug,
          });
          res.status(500).json({ error: 'Platform not installed for this rule' });
          return;
        }

        await persistSfRegistration(app.id, regKey, {
          secretKeyEnc: encryptToken(cachedResponse.secret),
          secretVersion: cachedResponse.secretVersion,
          registeredAt: token.redeemedAt || new Date().toISOString(),
          packageVersion: payload.packageVersion || 'unknown',
        });
        await markBootstrapTokenPersisted(payload.bootstrapToken);

        logInfo('SF registration: idempotent replay self-healed unpersisted secret', {
          sfOrgId: payload.sfOrgId,
          appId: app.id,
          regKey: regKey.substring(0, 26) + '...',
        });
      } else {
        logInfo('SF registration: idempotent replay returned cached response', {
          sfOrgId: payload.sfOrgId,
        });
      }
      res.status(200).json(cachedResponse);
      return;
    }

    // ─── 3. Resolve the OrgApp linked to this rule ───────────
    const app = await resolveOrgAppForRule(rule);

    if (!app) {
      logWarn('SF registration: no OrgApp found for rule', {
        ruleId: rule.id,
        appSlug: rule.appSlug,
      });
      // The bootstrap token was already redeemed at step 2 — we can't undo
      // that atomically. Return 500 so SF treats it as transient; the Apex
      // retry will hit the idempotent-replay self-heal above, which persists
      // the secret once the OrgApp exists.
      res.status(500).json({ error: 'Platform not installed for this rule' });
      return;
    }

    // ─── 4. Persist the encrypted secret, keyed per (SF org, webhook) ──
    // Composite keying: rule A and rule B of the same app, registered from
    // the same SF org, hold independent secrets — matching Apex's
    // per-webhookKey cache. See lib/sf-registration-key.ts.
    const encryptedSecret = encryptToken(payload.generatedSecret);
    const registration: SfRegistrationEntry = {
      secretKeyEnc: encryptedSecret,
      secretVersion,
      registeredAt: new Date().toISOString(),
      packageVersion: payload.packageVersion || 'unknown',
    };

    await persistSfRegistration(app.id, regKey, registration);

    // Gate for the replay self-heal. Best-effort: if marking fails, a future
    // replay redundantly re-writes the same secret — harmless.
    try {
      await markBootstrapTokenPersisted(payload.bootstrapToken);
    } catch (markErr: any) {
      logWarn('SF registration: failed to mark token persisted (replay will self-heal)', {
        sfOrgId: payload.sfOrgId,
        error: markErr?.message,
      });
    }

    logInfo('SF webhook registered', {
      orgId: rule.orgId,
      ruleId: rule.id,
      appId: app.id,
      sfOrgId: payload.sfOrgId,
      regKey: regKey.substring(0, 26) + '...',
      packageVersion: payload.packageVersion,
      webhookId,
    });

    res.status(200).json(responseBody);
  } catch (err) {
    next(err);
  }
}

router.post('/', handleSfRegistration);

export default router;
