import { z } from 'zod';
import { registry } from '../registry';
import { InstanceStatusEnum, IsoDate } from './common';

export const WorkflowInstanceSchema = registry.register(
  'WorkflowInstance',
  z.object({
    id: z.string().uuid(),
    orgId: z.string(),
    workflowId: z.string().uuid(),
    maestroInstanceId: z.string().optional(),
    instanceName: z.string(),
    status: InstanceStatusEnum,
    currentStep: z.string().optional(),
    lastCompletedStep: z.number().int().optional(),
    lastCompletedStepName: z.string().optional(),
    totalSteps: z.number().int().optional(),
    stepProgress: z.array(z.number()).optional(),
    triggerRuleId: z.string().optional(),
    triggerRuleName: z.string().optional(),
    triggerActionNumber: z.number().int().optional(),
    triggerEventId: z.string().optional(),
    sourcePlatform: z.string().optional(),
    inputData: z.record(z.any()).optional(),
    outputData: z.record(z.any()).optional(),
    envelopeId: z.string().optional(),
    envelopeStatus: z.enum(['sent', 'delivered', 'signed', 'completed', 'declined']).optional(),
    startedAt: IsoDate,
    completedAt: IsoDate.optional(),
    durationMs: z.number().int().optional(),
    errorMessage: z.string().optional(),
    errorStep: z.string().optional(),
    retryCount: z.number().int().nonnegative(),
    retrySequenceId: z.string().optional(),
    retryMaxAttempts: z.number().int().optional(),
    nextRetryAt: IsoDate.optional(),
    manuallyRetriedAt: IsoDate.optional(),
    manuallyCancelledAt: IsoDate.optional(),
    launchedBy: z.string().optional(),
    recordId: z.string().optional(),
    instanceUrl: z.string().url().optional(),
    tags: z.array(z.string()).optional(),
  }),
);
